#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HangManAssignment.Resource", IsApplication=true)]

namespace HangManAssignment
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::HangManAssignment.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.coordinatorLayoutStyle = global::HangManAssignment.Resource.Attribute.coordinatorLayoutStyle;
			global::Xamarin.Essentials.Resource.Attribute.font = global::HangManAssignment.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::HangManAssignment.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::HangManAssignment.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::HangManAssignment.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::HangManAssignment.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::HangManAssignment.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::HangManAssignment.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::HangManAssignment.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::HangManAssignment.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::HangManAssignment.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.keylines = global::HangManAssignment.Resource.Attribute.keylines;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchor = global::HangManAssignment.Resource.Attribute.layout_anchor;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchorGravity = global::HangManAssignment.Resource.Attribute.layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Attribute.layout_behavior = global::HangManAssignment.Resource.Attribute.layout_behavior;
			global::Xamarin.Essentials.Resource.Attribute.layout_dodgeInsetEdges = global::HangManAssignment.Resource.Attribute.layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Attribute.layout_insetEdge = global::HangManAssignment.Resource.Attribute.layout_insetEdge;
			global::Xamarin.Essentials.Resource.Attribute.layout_keyline = global::HangManAssignment.Resource.Attribute.layout_keyline;
			global::Xamarin.Essentials.Resource.Attribute.statusBarBackground = global::HangManAssignment.Resource.Attribute.statusBarBackground;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::HangManAssignment.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::HangManAssignment.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::HangManAssignment.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::HangManAssignment.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::HangManAssignment.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::HangManAssignment.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::HangManAssignment.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::HangManAssignment.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::HangManAssignment.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::HangManAssignment.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::HangManAssignment.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::HangManAssignment.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::HangManAssignment.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::HangManAssignment.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::HangManAssignment.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::HangManAssignment.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::HangManAssignment.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::HangManAssignment.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::HangManAssignment.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::HangManAssignment.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::HangManAssignment.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::HangManAssignment.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::HangManAssignment.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::HangManAssignment.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::HangManAssignment.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::HangManAssignment.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::HangManAssignment.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::HangManAssignment.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::HangManAssignment.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::HangManAssignment.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::HangManAssignment.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::HangManAssignment.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::HangManAssignment.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::HangManAssignment.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::HangManAssignment.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::HangManAssignment.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::HangManAssignment.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::HangManAssignment.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::HangManAssignment.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::HangManAssignment.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::HangManAssignment.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::HangManAssignment.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::HangManAssignment.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::HangManAssignment.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::HangManAssignment.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.action_container = global::HangManAssignment.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::HangManAssignment.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::HangManAssignment.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::HangManAssignment.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.actions = global::HangManAssignment.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.all = global::HangManAssignment.Resource.Id.all;
			global::Xamarin.Essentials.Resource.Id.async = global::HangManAssignment.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::HangManAssignment.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.bottom = global::HangManAssignment.Resource.Id.bottom;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::HangManAssignment.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::HangManAssignment.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::HangManAssignment.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::HangManAssignment.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::HangManAssignment.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.center = global::HangManAssignment.Resource.Id.center;
			global::Xamarin.Essentials.Resource.Id.center_horizontal = global::HangManAssignment.Resource.Id.center_horizontal;
			global::Xamarin.Essentials.Resource.Id.center_vertical = global::HangManAssignment.Resource.Id.center_vertical;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::HangManAssignment.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.clip_horizontal = global::HangManAssignment.Resource.Id.clip_horizontal;
			global::Xamarin.Essentials.Resource.Id.clip_vertical = global::HangManAssignment.Resource.Id.clip_vertical;
			global::Xamarin.Essentials.Resource.Id.end = global::HangManAssignment.Resource.Id.end;
			global::Xamarin.Essentials.Resource.Id.fill = global::HangManAssignment.Resource.Id.fill;
			global::Xamarin.Essentials.Resource.Id.fill_horizontal = global::HangManAssignment.Resource.Id.fill_horizontal;
			global::Xamarin.Essentials.Resource.Id.fill_vertical = global::HangManAssignment.Resource.Id.fill_vertical;
			global::Xamarin.Essentials.Resource.Id.forever = global::HangManAssignment.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::HangManAssignment.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::HangManAssignment.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::HangManAssignment.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::HangManAssignment.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.left = global::HangManAssignment.Resource.Id.left;
			global::Xamarin.Essentials.Resource.Id.line1 = global::HangManAssignment.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::HangManAssignment.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.none = global::HangManAssignment.Resource.Id.none;
			global::Xamarin.Essentials.Resource.Id.normal = global::HangManAssignment.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::HangManAssignment.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::HangManAssignment.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::HangManAssignment.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right = global::HangManAssignment.Resource.Id.right;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::HangManAssignment.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::HangManAssignment.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.start = global::HangManAssignment.Resource.Id.start;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::HangManAssignment.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::HangManAssignment.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::HangManAssignment.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::HangManAssignment.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::HangManAssignment.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::HangManAssignment.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::HangManAssignment.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Id.top = global::HangManAssignment.Resource.Id.top;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::HangManAssignment.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::HangManAssignment.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::HangManAssignment.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::HangManAssignment.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::HangManAssignment.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::HangManAssignment.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::HangManAssignment.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::HangManAssignment.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::HangManAssignment.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::HangManAssignment.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::HangManAssignment.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::HangManAssignment.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::HangManAssignment.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::HangManAssignment.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::HangManAssignment.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::HangManAssignment.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::HangManAssignment.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Style.Widget_Support_CoordinatorLayout = global::HangManAssignment.Resource.Style.Widget_Support_CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::HangManAssignment.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::HangManAssignment.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::HangManAssignment.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::HangManAssignment.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::HangManAssignment.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout = global::HangManAssignment.Resource.Styleable.CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_keylines = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_keylines;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_Layout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::HangManAssignment.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::HangManAssignment.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::HangManAssignment.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::HangManAssignment.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::HangManAssignment.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::HangManAssignment.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::HangManAssignment.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::HangManAssignment.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::HangManAssignment.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::HangManAssignment.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::HangManAssignment.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::HangManAssignment.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::HangManAssignment.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::HangManAssignment.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::HangManAssignment.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::HangManAssignment.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::HangManAssignment.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::HangManAssignment.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::HangManAssignment.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::HangManAssignment.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::HangManAssignment.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::HangManAssignment.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::HangManAssignment.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::HangManAssignment.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::HangManAssignment.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::HangManAssignment.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::HangManAssignment.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::HangManAssignment.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::HangManAssignment.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::HangManAssignment.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::HangManAssignment.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::HangManAssignment.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::HangManAssignment.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::HangManAssignment.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::HangManAssignment.Resource.Styleable.GradientColorItem_android_offset;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int coordinatorLayoutStyle = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int font = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fontProviderAuthority = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fontProviderCerts = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fontProviderFetchStrategy = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderFetchTimeout = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontProviderPackage = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontProviderQuery = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontStyle = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontVariationSettings = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fontWeight = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int keylines = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int layout_anchor = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int layout_anchorGravity = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int layout_behavior = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int layout_dodgeInsetEdges = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int layout_insetEdge = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int layout_keyline = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int statusBarBackground = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int ttcIndex = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int browser_actions_bg_grey = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int browser_actions_divider_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int browser_actions_text_color = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int browser_actions_title_color = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int notification_action_color_filter = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int notification_icon_bg_color = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int ripple_material_light = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int secondary_text_default_material_light = 2130837511;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int browser_actions_context_menu_max_width = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int browser_actions_context_menu_min_padding = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int compat_button_inset_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_inset_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_button_padding_horizontal_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_button_padding_vertical_material = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_control_corner_material = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int compat_notification_large_icon_max_height = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int compat_notification_large_icon_max_width = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int notification_action_icon_size = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int notification_action_text_size = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int notification_big_circle_margin = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int notification_content_margin_start = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int notification_large_icon_height = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int notification_large_icon_width = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int notification_main_column_padding_top = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_media_narrow_margin = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_right_icon_size = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_right_side_padding_top = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_small_icon_background_padding = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_small_icon_size_as_large = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_subtext_size = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int notification_top_pad = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int notification_top_pad_large_text = 2130903063;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int btnStart = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int CatActors = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int CatAnimals = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int CatClothes = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int CatComputers = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int CatCountries = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int category = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int CatFood = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int CatHumanBody = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int CatMovies = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int CatMusicalInstruments = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int CatSongs = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int Hangman1 = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int Hangman2 = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int Hangman3 = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int Hangman4 = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int Hangman5 = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int Hangman6 = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int Hangman7 = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int Hangman8 = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int Hangman9 = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int HiScore = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int Icon = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int L_A = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int L_B = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int L_Blank = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int L_BlankSpace = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int L_C = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int L_D = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int L_E = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int L_F = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int L_G = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int L_H = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int L_I = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int L_J = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int L_K = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int L_L = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int L_M = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int L_N = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int L_O = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int L_P = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int L_Q = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int L_R = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public const int L_S = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public const int L_T = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public const int L_U = 2130968621;
			
			// aapt resource value: 0x7F04002E
			public const int L_V = 2130968622;
			
			// aapt resource value: 0x7F04002F
			public const int L_W = 2130968623;
			
			// aapt resource value: 0x7F040030
			public const int L_X = 2130968624;
			
			// aapt resource value: 0x7F040031
			public const int L_Y = 2130968625;
			
			// aapt resource value: 0x7F040032
			public const int L_Z = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int no1 = 2130968627;
			
			// aapt resource value: 0x7F040034
			public const int no10 = 2130968628;
			
			// aapt resource value: 0x7F040035
			public const int no2 = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int no3 = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int no4 = 2130968631;
			
			// aapt resource value: 0x7F040038
			public const int no5 = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int no6 = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int no7 = 2130968634;
			
			// aapt resource value: 0x7F04003B
			public const int no8 = 2130968635;
			
			// aapt resource value: 0x7F04003C
			public const int no9 = 2130968636;
			
			// aapt resource value: 0x7F04003D
			public const int notification_action_background = 2130968637;
			
			// aapt resource value: 0x7F04003E
			public const int notification_bg = 2130968638;
			
			// aapt resource value: 0x7F04003F
			public const int notification_bg_low = 2130968639;
			
			// aapt resource value: 0x7F040040
			public const int notification_bg_low_normal = 2130968640;
			
			// aapt resource value: 0x7F040041
			public const int notification_bg_low_pressed = 2130968641;
			
			// aapt resource value: 0x7F040042
			public const int notification_bg_normal = 2130968642;
			
			// aapt resource value: 0x7F040043
			public const int notification_bg_normal_pressed = 2130968643;
			
			// aapt resource value: 0x7F040044
			public const int notification_icon_background = 2130968644;
			
			// aapt resource value: 0x7F040045
			public const int notification_template_icon_bg = 2130968645;
			
			// aapt resource value: 0x7F040046
			public const int notification_template_icon_low_bg = 2130968646;
			
			// aapt resource value: 0x7F040047
			public const int notification_tile_bg = 2130968647;
			
			// aapt resource value: 0x7F040048
			public const int notify_panel_notification_icon_bg = 2130968648;
			
			// aapt resource value: 0x7F040049
			public const int score = 2130968649;
			
			// aapt resource value: 0x7F04004A
			public const int score2 = 2130968650;
			
			// aapt resource value: 0x7F04004B
			public const int SpacerHalf = 2130968651;
			
			// aapt resource value: 0x7F04004C
			public const int SplashLogo = 2130968652;
			
			// aapt resource value: 0x7F04004D
			public const int TitleScreen = 2130968653;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050009
			public const int actions = 2131034121;
			
			// aapt resource value: 0x7F050005
			public const int action_container = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int action_divider = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int action_image = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int action_text = 2131034120;
			
			// aapt resource value: 0x7F05000A
			public const int all = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int async = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int blocking = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int bottom = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int browser_actions_header_text = 2131034126;
			
			// aapt resource value: 0x7F050011
			public const int browser_actions_menu_items = 2131034129;
			
			// aapt resource value: 0x7F05000F
			public const int browser_actions_menu_item_icon = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int browser_actions_menu_item_text = 2131034128;
			
			// aapt resource value: 0x7F050012
			public const int browser_actions_menu_view = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int btnOK = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int btnPlay = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int btn_A = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int btn_B = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int btn_C = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int btn_D = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int btn_E = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int btn_F = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int btn_G = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int btn_H = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int btn_I = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int btn_J = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int btn_K = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int btn_L = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int btn_M = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int btn_N = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int btn_O = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int btn_P = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int btn_Q = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int btn_R = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int btn_S = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int btn_T = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int btn_U = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int btn_V = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int btn_W = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int btn_X = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int btn_Y = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int btn_Z = 2131034158;
			
			// aapt resource value: 0x7F050000
			public const int Cat = 2131034112;
			
			// aapt resource value: 0x7F05002F
			public const int center = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int center_horizontal = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int center_vertical = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int chronometer = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int clip_horizontal = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int clip_vertical = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int editName = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int end = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int fill = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int fill_horizontal = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int fill_vertical = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int forever = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public const int icon = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int icon_group = 2131034172;
			
			// aapt resource value: 0x7F050001
			public const int Image = 2131034113;
			
			// aapt resource value: 0x7F05003D
			public const int imageView1 = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public const int imageView_SplashLogo = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public const int imgHangman = 2131034175;
			
			// aapt resource value: 0x7F050040
			public const int imgHiScore = 2131034176;
			
			// aapt resource value: 0x7F050041
			public const int imgNo1 = 2131034177;
			
			// aapt resource value: 0x7F050042
			public const int imgNo10 = 2131034178;
			
			// aapt resource value: 0x7F050043
			public const int imgNo2 = 2131034179;
			
			// aapt resource value: 0x7F050044
			public const int imgNo3 = 2131034180;
			
			// aapt resource value: 0x7F050045
			public const int imgNo4 = 2131034181;
			
			// aapt resource value: 0x7F050046
			public const int imgNo5 = 2131034182;
			
			// aapt resource value: 0x7F050047
			public const int imgNo6 = 2131034183;
			
			// aapt resource value: 0x7F050048
			public const int imgNo7 = 2131034184;
			
			// aapt resource value: 0x7F050049
			public const int imgNo8 = 2131034185;
			
			// aapt resource value: 0x7F05004A
			public const int imgNo9 = 2131034186;
			
			// aapt resource value: 0x7F05004B
			public const int imgSpacer1 = 2131034187;
			
			// aapt resource value: 0x7F05004C
			public const int imgSpacer2 = 2131034188;
			
			// aapt resource value: 0x7F05004D
			public const int info = 2131034189;
			
			// aapt resource value: 0x7F05004E
			public const int italic = 2131034190;
			
			// aapt resource value: 0x7F05004F
			public const int left = 2131034191;
			
			// aapt resource value: 0x7F050050
			public const int line1 = 2131034192;
			
			// aapt resource value: 0x7F050051
			public const int line3 = 2131034193;
			
			// aapt resource value: 0x7F050052
			public const int linearLayout1 = 2131034194;
			
			// aapt resource value: 0x7F050053
			public const int linearLayout3 = 2131034195;
			
			// aapt resource value: 0x7F050054
			public const int linearLayout4 = 2131034196;
			
			// aapt resource value: 0x7F050002
			public const int LinTop = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int LinWord = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int List = 2131034116;
			
			// aapt resource value: 0x7F050055
			public const int none = 2131034197;
			
			// aapt resource value: 0x7F050056
			public const int normal = 2131034198;
			
			// aapt resource value: 0x7F050057
			public const int notification_background = 2131034199;
			
			// aapt resource value: 0x7F050058
			public const int notification_main_column = 2131034200;
			
			// aapt resource value: 0x7F050059
			public const int notification_main_column_container = 2131034201;
			
			// aapt resource value: 0x7F05005A
			public const int relative1 = 2131034202;
			
			// aapt resource value: 0x7F05005B
			public const int relativeLayout1 = 2131034203;
			
			// aapt resource value: 0x7F05005C
			public const int right = 2131034204;
			
			// aapt resource value: 0x7F05005D
			public const int right_icon = 2131034205;
			
			// aapt resource value: 0x7F05005E
			public const int right_side = 2131034206;
			
			// aapt resource value: 0x7F05005F
			public const int space1 = 2131034207;
			
			// aapt resource value: 0x7F050060
			public const int start = 2131034208;
			
			// aapt resource value: 0x7F050061
			public const int tag_transition_group = 2131034209;
			
			// aapt resource value: 0x7F050062
			public const int tag_unhandled_key_event_manager = 2131034210;
			
			// aapt resource value: 0x7F050063
			public const int tag_unhandled_key_listeners = 2131034211;
			
			// aapt resource value: 0x7F050064
			public const int text = 2131034212;
			
			// aapt resource value: 0x7F050065
			public const int text2 = 2131034213;
			
			// aapt resource value: 0x7F050066
			public const int time = 2131034214;
			
			// aapt resource value: 0x7F050067
			public const int title = 2131034215;
			
			// aapt resource value: 0x7F050068
			public const int top = 2131034216;
			
			// aapt resource value: 0x7F050069
			public const int txtAnswer = 2131034217;
			
			// aapt resource value: 0x7F05006A
			public const int txtEnterName = 2131034218;
			
			// aapt resource value: 0x7F05006B
			public const int txtLose = 2131034219;
			
			// aapt resource value: 0x7F05006C
			public const int txtScore = 2131034220;
			
			// aapt resource value: 0x7F05006D
			public const int txtScore1 = 2131034221;
			
			// aapt resource value: 0x7F05006E
			public const int txtScore10 = 2131034222;
			
			// aapt resource value: 0x7F05006F
			public const int txtScore2 = 2131034223;
			
			// aapt resource value: 0x7F050070
			public const int txtScore3 = 2131034224;
			
			// aapt resource value: 0x7F050071
			public const int txtScore4 = 2131034225;
			
			// aapt resource value: 0x7F050072
			public const int txtScore5 = 2131034226;
			
			// aapt resource value: 0x7F050073
			public const int txtScore6 = 2131034227;
			
			// aapt resource value: 0x7F050074
			public const int txtScore7 = 2131034228;
			
			// aapt resource value: 0x7F050075
			public const int txtScore8 = 2131034229;
			
			// aapt resource value: 0x7F050076
			public const int txtScore9 = 2131034230;
			
			// aapt resource value: 0x7F050077
			public const int txtWordWas = 2131034231;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int status_bar_notification_info_maxnum = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int browser_actions_context_menu_page = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int browser_actions_context_menu_row = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int layoutCategory = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int layoutCategoryRow = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int layoutGame = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int LayoutHiScore = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int layoutPopUp = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int layoutTitle = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int Main = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int notification_action = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int notification_action_tombstone = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int notification_template_custom_big = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int notification_template_icon_group = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int notification_template_part_chronometer = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int notification_template_part_time = 2131165198;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int status_bar_notification_info_overflow = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int TextAppearance_Compat_Notification_Line2 = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int TextAppearance_Compat_Notification_Time = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int TextAppearance_Compat_Notification_Title = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int Theme_PopTheme = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int Widget_Compat_NotificationActionContainer = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int Widget_Compat_NotificationActionText = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int Widget_Support_CoordinatorLayout = 2131296264;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F01000C,0x7F010013 }
			public static int[] CoordinatorLayout = new int[] {
					2130771980,
					2130771987};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008 }
			public static int[] FontFamily = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010002,0x7F010009,0x7F01000A,0x7F01000B,0x7F010014 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771970,
					2130771977,
					2130771978,
					2130771979,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0B0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131427328;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
